apiVersion: apps/v1
kind: Deployment
metadata:
  name: devportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devportal
  template:
    metadata:
      labels:
        app: devportal
    spec:
      containers:
        - name: devportal
          image: {{ .Values.devportal.image }}
          ports:
            - containerPort: {{ .Values.devportal.port }}
          env:
            - name: SPRING_ELASTICSEARCH_REST_URIS
              value: {{ .Values.devportal.environment.SPRING_ELASTICSEARCH_REST_URIS }}
---
apiVersion: v1
kind: Service
metadata:
  name: devportal-service
spec:
  selector:  # Corrected indentation
    app: devportal
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8083
  type: NodePort

