apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-deployment
    labels:
        tier: database
spec:
    selector:
      matchLabels:
        app: myapp
    template:
      metadata:
        name: redis-1
        labels:
          app: myapp
      spec:
        containers:
        - name: nginx
          image: nginx
    replicas: 6