#!/bin/bash
#Author: jaganathan

file=$(find /home/jaganathan/data -name "sample.txt" -type f)


if [ -n "$file" ];
then
    cp "$file" /tmp/found.txt.
    echo "File found and copied to /tmp/found.txt."
else
    echo "File not found."
fi

