#!/bin/bash
# author : jagan
# des: user account magangment process

#!/bin/bash

echo "Enter the user name"
read name

if grep -q "^$name:" /etc/passwd; then
	    echo "User already exists. Try another username."
	        exit 1
fi

echo "Provide the details of the username"
read des

echo "Do you want to create a user id? (Y/N)"
read check

if [ "$check" == "Y" ]; then
	    echo "Enter the user id"
	        read id
		    useradd -c "$des" -u "$id" "$name"
		        if [ $? -eq 0 ]; then
				        echo "User id and account have been created"
					    else
						            echo "Failed to create the user id and account"
							        fi

							elif [ "$check" == "N" ]; then
								    useradd -c "$des" "$name"
								        if [ $? -eq 0 ]; then
										        echo "User id cannot be created. Account is created successfully"
											    else
												            echo "Failed to create the account"
													        fi

													else
														    echo "Invalid input. Please enter Y or N."
														        exit 1
fi


