name: Update PR
 
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
 
jobs:
  update-readme:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Run update script
        run: | 
            sudo chmod 777 update-readme.sh
            ./update-readme.sh
            
      - name: Commit and push changes
        run: |
          git config user.email "jagakarthi11@gmail.com"
          git config user.name "Jaganathan-01"
          git checkout -b master  # Create and checkout main branch if not exists
          git pull origin master --allow-unrelated-histories 
          git add output/readme.txt
          git commit -m "Update readme with PR info"
          git push origin HEAD:master

